---
title: "3. Data integration"
author: "Cankun Wang"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(error = FALSE)
library(Seurat)
library(cowplot)
library(dplyr)
library(ggplot2)
library(patchwork)
library(here)
library(qs)
library(Polychrome)

```


# Set working dir

```{r,echo=F,eval=T,message=F,warning=F,error=F}

here::i_am("3_integration.rmd")
here::set_here()
print(paste("Current working directory:", here::here()))

```

# Load data

```{r,echo=F,eval=T,message=F,warning=F,error=F}

combined <- qs::qread('combined.qsave')
```

# Integration

```{r,echo=F,eval=T,message=F,warning=F,error=F}

combine.list <- SplitObject(combined, split.by = "orig.ident")

combine.list <- lapply(
  X = combine.list,
  FUN = function(x) {
    x <- NormalizeData(x)
    x <-
      FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
  }
)


```

# Dimension reduction

```{r,echo=F,eval=T,message=F,warning=F,error=F}
days <- c("0", "2", "5", "10", "14", "30")

i = 30
for(i in days) {
  this_days <- c(paste0("Con", i), paste0("N1KO", i))
  sample_idx <- which(names(combine.list) %in% this_days)
  sub_list <- combine.list[sample_idx]
  combine.anchors <-
    FindIntegrationAnchors(object.list = sub_list, dims = 1:20)
  sub_combined <-
    IntegrateData(anchorset = combine.anchors, dims = 1:20)
  DefaultAssay(sub_combined) <- "integrated"
  sub_combined <- ScaleData(sub_combined, verbose = FALSE)
  sub_combined <- RunPCA(sub_combined, npcs = 20, verbose = FALSE)
  sub_combined <-
    RunUMAP(sub_combined, reduction = "pca", dims = 1:20)
  sub_combined <-
    FindNeighbors(sub_combined, reduction = "pca", dims = 1:20)
  sub_combined <- FindClusters(sub_combined, resolution = 0.2)
  
  Idents(combined) <- combined$orig.ident
  this_combind <- subset(combined, idents = this_days)
  sub_combined <-
    AddMetaData(sub_combined, this_combind$cell_type, col.name = "cell_type")
  qs::qsave(sub_combined, paste0("../integration/day", i, ".qsave"))
}

```



```{r,echo=F,eval=F,message=F,warning=F,error=F, fig.width=10}
sub_combined <- qs::qread("../integration/day14.qsave")
DimPlot(
  sub_combined,
  reduction = "umap",
  cols = as.vector(palette36.colors(36)[-2]),
  label = T
)

DimPlot(
  sub_combined,
  reduction = "umap",
  group.by = "orig.ident",
  cols = as.vector(palette36.colors(36)[-2]),
  label = T
)

DimPlot(
  sub_combined,
  reduction = "umap",
  group.by = "cell_type",
  cols = as.vector(palette36.colors(36)[-2]),
  label = T
)

DimPlot(
  sub_combined,
  reduction = "umap",
  group.by = "cell_type",
  split.by = "orig.ident",
  cols = as.vector(palette36.colors(36)[-2]),
  label = T
)

FeaturePlot(sub_combined)

```


```{r,echo=F,eval=F,message=F,warning=F,error=F}
# Re-order the time 
combined$orig.ident <- factor(combined$orig.ident, levels = levels(as.factor(combined$orig.ident))[c(1,4,6,2,3,5,7,10,12,8,9,11)])
```

```{r,echo=F,eval=T,message=FALSE,warning=F}

qs::qsave(combined, "combined.qsave") 

```

# Session info

```{r,echo=F,eval=T,message=F,warning=F}
sessionInfo()
```
