---
title: "DEG"
author: "Cankun Wang"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Seurat)
library(cowplot)
library(dplyr)
library(ggplot2)
library(patchwork)
library(here)
library(qs)
library(Polychrome)
library(RColorBrewer)
library(tidyverse)
library(fgsea)
library(msigdbr)
library(monocle3)
library(batchelor)
library(EnhancedVolcano)
library(Matrix.utils)
#BiocManager::install(c('batchelor', 'Matrix.utils'))
```


# Set working dir

```{r,echo=F,eval=T,message=F,warning=F,error=F}
here::i_am("5.Rmd")
here::set_here()
print(paste("Current working directory:", here::here()))

```

# Load data

```{r,echo=F,eval=T,message=F,warning=F,error=F}
source("functions.R")
####

#combined <- readRDS("combined.rds")
combined <- qs::qread('combined.qsave')
####

DefaultAssay(combined) <- "RNA"
Idents(combined) <- combined$seurat_clusters
custom_color <-
  as.character(palette36.colors(36)[-2])[1:length(levels(Idents(combined)))]


provided_marker <- read.csv("provided_marker_manual.csv", header = T)
provided_marker$cell_type <- as.factor(provided_marker$cell_type)

Idents(combined) <- combined$orig.ident
DefaultAssay(combined) <- "RNA"
i = 1
j = 1
k = 1

```

# DEG

```{r,echo=F,eval=F,message=FALSE,warning=F}
dir.create('result')
dir.create('result/cell_type')
dir.create('result/deg')

Idents(combined) <- combined$orig.ident

table(combined$seurat_clusters)
empty_category <- as.factor(combined$orig.ident)
levels(empty_category) <-
  rep("empty_category", length(levels(empty_category)))
combined <-
  AddMetaData(combined, metadata = empty_category, col.name = "empty_category")


Idents(combined) <- combined$empty_category
DefaultAssay(combined) <- "RNA"
idx = 7
i = 7
j = 9
k = 2
# seq_along(levels(provided_marker$cell_type))
for (idx in 8:14) {
  this_ct <- levels(provided_marker$cell_type)[idx]
  this_markers <- provided_marker %>%
    filter(cell_type == this_ct) %>%
    pull(gene)
  this_direction <- provided_marker %>%
    filter(cell_type == this_ct) %>%
    pull(direction)
  this_data <- FetchData(object = combined, vars = this_markers)
  selected_cells <- rownames(this_data)
  for (k in seq_along(this_markers)) {
    if (this_direction[k] == "pos") {
      this_cells <- this_data %>%
        filter(get(this_markers[k]) >  0.1) %>%
        rownames_to_column("cell") %>%
        pull(cell)
      selected_cells <- intersect(selected_cells, this_cells)
    } else{
      this_cells <- this_data %>%
        filter(get(this_markers[k]) <= 0) %>%
        rownames_to_column("cell") %>%
        pull(cell)
      selected_cells <- intersect(selected_cells, this_cells)
    }
  }
  
  selected_cells <- unique(selected_cells)
  this_obj <- combined[, selected_cells]
  
  combined@meta.data$tmp_ct <-
    ifelse(rownames(combined@meta.data) %in% colnames(this_obj),
           "positive",
           "negative")
  library(tidyverse)
  
  Idents(combined) <- combined$tmp_ct
  custom_color <- c('#C0C0C0', '#B00D23')
  
  # cell type UMAP
  p1 <-
    DimPlot(
      combined,
      reduction = "umap",
      group.by = "tmp_ct",
      split.by = "orig.ident",
      cols = custom_color,
      combine = F,
      pt.size = 0.5,
      ncol = 6
    )[[1]] + NoLegend() + ggplot2::theme(legend.position = "top") + ggtitle(this_ct)
  
  
  png(
    paste0('result/cell_type/', this_ct, "_marker_umap.png"),
    width = 4000,
    height = 1800,
    res = 300
  )
  print(p1)
  dev.off()
  
  # cell type frequency table
  write.csv(
    table(combined$tmp_ct, combined$orig.ident),
    paste0('result/cell_type/', this_ct, "_freq.csv")
  )
  
  # DEG
  Idents(combined) <- combined$orig.ident
  
  j = levels(as.factor(combined$orig.ident))[6]
  for (j in levels(as.factor(combined$orig.ident))) {
    this_1 <- levels(as.factor(combined$tmp_ct))[2]
    this_2 <- levels(as.factor(combined$tmp_ct))[1]
    this_sample <- j
    
    this_combined <- subset(combined, idents = this_sample)
    RESULT_DIR <-
      paste0("./result/deg/",
             this_sample,
             "_",
             this_ct,
             "_",
             this_1,
             "_vs_",
             this_2,
             "/")
    
    if (length(levels(as.factor(this_combined$tmp_ct))) > 1 & all(table(this_combined$tmp_ct) > 5)) {
      dir.create(RESULT_DIR, showWarnings = F)
      Idents(this_combined) <- this_combined$tmp_ct
      DefaultAssay(this_combined) <- "RNA"
      cts_markers <-
        FindMarkers(this_combined,
                    ident.1 = this_1,
                    ident.2 = this_2) %>%
        rownames_to_column("gene") %>%
        filter(p_val_adj < 0.05)
      
      avg_expr_deg <-
        AverageExpression(this_combined, features = cts_markers$gene)$RNA %>%
        as.data.frame() %>%
        rownames_to_column("gene") %>%
        dplyr::rename(group1_expr=positive, group2_expr=negative)

      cts_markers <- cts_markers %>%
        left_join(avg_expr_deg, by="gene") %>%
        arrange(desc(avg_log2FC))
      
      cts_markers %>%
        write_csv(paste0(RESULT_DIR, "deg.csv"))
      
      
       
      library(enrichR)
      dbs <-
        c(
          "GO_Molecular_Function_2018",
          "GO_Cellular_Component_2018",
          "GO_Biological_Process_2018",
          "KEGG_2019_Human"
        )
      
      
      this_up <- cts_markers %>%
        filter(avg_log2FC > 0) %>%
        pull(gene)
      this_down <- cts_markers %>%
        filter(avg_log2FC < 0) %>%
        pull(gene)
      
      # Volcano
      if (length(this_up) > 10 &
          length(this_down) > 10) {
        top_up <- cts_markers %>%
          top_n(10, avg_log2FC) %>%
          pull(gene)
        top_down <- cts_markers %>%
          top_n(-10, avg_log2FC) %>%
          pull(gene)
        
        p1 <- EnhancedVolcano(
          cts_markers,
          lab = cts_markers$gene,
          x = 'avg_log2FC',
          y = 'p_val_adj',
          selectLab = c(top_up, top_down),
          pCutoff = 0.05,
          FCcutoff = 0.25,
        )
        png(
          paste0(RESULT_DIR, "volcano.png"),
          width = 3000,
          height = 3000,
          res = 300
        )
        print(p1)
        dev.off()
        
      }
      
      
      ### UP
      if (length(this_up) > 10) {
      enriched_combined <- enrichr(this_up, dbs)
      enriched_combined <- lapply(enriched_combined, function(x) {
        x$Overlap <- paste0(" ", x$Overlap)
        return(x[, c(-5, -6)])
      })
      
      for (idx in seq_along(enriched_combined)) {
        this_res <- enriched_combined[[idx]]
        this_name <- names(enriched_combined[idx])
        
        this_selected_terms <- this_res[1:10, ]
        enrichment_dotplot(
          this_selected_terms,
          filename = paste0(RESULT_DIR,
                            "enrich_plot_top10_up_",
                            this_name,
                            ".png")
        )
      }
      write.csv(
        enriched_combined$GO_Molecular_Function_2018,
        paste0(RESULT_DIR, "GO_MF_up.csv")
      )
      write.csv(
        enriched_combined$GO_Cellular_Component_2018,
        paste0(RESULT_DIR, "GO_CC_up.csv")
      )
      write.csv(
        enriched_combined$GO_Biological_Process_2018,
        paste0(RESULT_DIR, "GO_BP_up.csv")
      )
      write.csv(enriched_combined$KEGG_2019_Human,
                paste0(RESULT_DIR, "KEGG_up.csv"))
      
      }
      ### DOWN
      if (length(this_down) > 10) {
      enriched_combined <- enrichr(this_down, dbs)
      enriched_combined <- lapply(enriched_combined, function(x) {
        x$Overlap <- paste0(" ", x$Overlap)
        return(x[, c(-5, -6)])
      })
      
      for (idx in seq_along(enriched_combined)) {
        this_res <- enriched_combined[[idx]]
        this_name <- names(enriched_combined[idx])
        #this_match_idx <- which(!is.na(str_extract(this_res$Term, keywords)))
        
        ## this_selected_terms <- this_res[1:20, ]
        ## enrichment_dotplot(
        ##   this_selected_terms,
        ##   filename = paste0(
        ##     RESULT_DIR,
        ##     "enrich_plot_top20_down_",
        ##     this_name,
        ##     ".png"
        ##   )
        ## )
        this_selected_terms <- this_res[1:10, ]
        enrichment_dotplot(
          this_selected_terms,
          filename = paste0(
            RESULT_DIR,
            "enrich_plot_top10_down_",
            this_name,
            ".png"
          )
        )
      }
      write.csv(
        enriched_combined$GO_Molecular_Function_2018,
        paste0(RESULT_DIR, "GO_MF_down.csv")
      )
      write.csv(
        enriched_combined$GO_Cellular_Component_2018,
        paste0(RESULT_DIR, "GO_CC_down.csv")
      )
      write.csv(
        enriched_combined$GO_Biological_Process_2018,
        paste0(RESULT_DIR, "GO_BP_down.csv")
      )
      write.csv(enriched_combined$KEGG_2019_Human,
                paste0(RESULT_DIR, "KEGG_down.csv"))
      
       
      }
    }
    
  }
  
  Idents(combined) <- combined$tmp_ct
  this_positive <- levels(Idents(combined))[2]
  this_combined <- subset(combined, idents = this_positive)
  Idents(this_combined) <- this_combined$orig.ident
  ## DEG: con vs con
  idx = 1
  i=5 
  j=6
  for (i in 1:6) {
    for (j in 1:6) {
      this_1 <- levels(as.factor(this_combined$orig.ident))[j]
      this_2 <- levels(as.factor(this_combined$orig.ident))[i]
      if (this_1 != this_2 &
          !is.na(this_1) & !is.na(this_2) & j > i) {
        RESULT_DIR <-
          paste0("./result/deg/",
                 this_ct,
                 "_positive_",
                 this_1,
                 "_vs_",
                 this_2,
                 "/")
    table1 <- table(this_combined$orig.ident)
    tmp1 <- as.numeric(table1[which(names(table1) == this_1)])
    tmp2 <- as.numeric(table1[which(names(table1) == this_2)])
    
    if (tmp1 > 10 & tmp2 > 10) {
      dir.create(RESULT_DIR, showWarnings = F)
      Idents(this_combined) <- this_combined$orig.ident
      DefaultAssay(this_combined) <- "RNA"
      cts_markers <-
        FindMarkers(this_combined,
                    ident.1 = this_1,
                    ident.2 = this_2) %>%
        rownames_to_column("gene") %>%
        filter(p_val_adj < 0.05)
      
      avg_expr_deg <-
        AverageExpression(this_combined, features = cts_markers$gene)$RNA %>%
        as.data.frame() %>%
        rownames_to_column("gene") %>%
        dplyr::select(gene,`this_1`,`this_2`)

      cts_markers <- cts_markers %>%
        left_join(avg_expr_deg, by="gene") %>%
        arrange(desc(avg_log2FC))
      
      cts_markers %>%
        write_csv(paste0(RESULT_DIR, "deg.csv"))
      
      
       
      library(enrichR)
      dbs <-
        c(
          "GO_Molecular_Function_2018",
          "GO_Cellular_Component_2018",
          "GO_Biological_Process_2018",
          "KEGG_2019_Human"
        )
      
      
      this_up <- cts_markers %>%
        filter(avg_log2FC > 0) %>%
        pull(gene)
      this_down <- cts_markers %>%
        filter(avg_log2FC < 0) %>%
        pull(gene)
      
      # Volcano
      if (length(this_up) > 10 &
          length(this_down) > 10) {
        top_up <- cts_markers %>%
          top_n(10, avg_log2FC) %>%
          pull(gene)
        top_down <- cts_markers %>%
          top_n(-10, avg_log2FC) %>%
          pull(gene)
        
        p1 <- EnhancedVolcano(
          cts_markers,
          lab = cts_markers$gene,
          x = 'avg_log2FC',
          y = 'p_val_adj',
          selectLab = c(top_up, top_down),
          pCutoff = 0.05,
          FCcutoff = 0.25,
        )
        png(
          paste0(RESULT_DIR, "volcano.png"),
          width = 3000,
          height = 3000,
          res = 300
        )
        print(p1)
        dev.off()
        
      }
      
     

      ### UP
      if (length(this_up) > 10) {
      enriched_combined <- enrichr(this_up, dbs)
      enriched_combined <- lapply(enriched_combined, function(x) {
        x$Overlap <- paste0(" ", x$Overlap)
        return(x[, c(-5, -6)])
      })
      
      for (idx in seq_along(enriched_combined)) {
        this_res <- enriched_combined[[idx]]
        this_name <- names(enriched_combined[idx])
        #this_match_idx <- which(!is.na(str_extract(this_res$Term, keywords)))
        
        ## this_selected_terms <- this_res[1:20, ]
        ## enrichment_dotplot(
        ##   this_selected_terms,
        ##   filename = paste0(RESULT_DIR,
        ##                     "enrich_plot_top20_up_",
        ##                     this_name,
        ##                     ".png")
        ## )
        this_selected_terms <- this_res[1:10, ]
        enrichment_dotplot(
          this_selected_terms,
          filename = paste0(RESULT_DIR,
                            "enrich_plot_top10_up_",
                            this_name,
                            ".png")
        )
      }
      write.csv(
        enriched_combined$GO_Molecular_Function_2018,
        paste0(RESULT_DIR, "GO_MF_up.csv")
      )
      write.csv(
        enriched_combined$GO_Cellular_Component_2018,
        paste0(RESULT_DIR, "GO_CC_up.csv")
      )
      write.csv(
        enriched_combined$GO_Biological_Process_2018,
        paste0(RESULT_DIR, "GO_BP_up.csv")
      )
      write.csv(enriched_combined$KEGG_2019_Human,
                paste0(RESULT_DIR, "KEGG_up.csv"))
      
      }
      ### DOWN
      if (length(this_down) > 10) {
      enriched_combined <- enrichr(this_down, dbs)
      enriched_combined <- lapply(enriched_combined, function(x) {
        x$Overlap <- paste0(" ", x$Overlap)
        return(x[, c(-5, -6)])
      })
      
      for (idx in seq_along(enriched_combined)) {
        this_res <- enriched_combined[[idx]]
        this_name <- names(enriched_combined[idx])
        #this_match_idx <- which(!is.na(str_extract(this_res$Term, keywords)))
        
        ## this_selected_terms <- this_res[1:20, ]
        ## enrichment_dotplot(
        ##   this_selected_terms,
        ##   filename = paste0(
        ##     RESULT_DIR,
        ##     "enrich_plot_top20_down_",
        ##     this_name,
        ##     ".png"
        ##   )
        ## )
        this_selected_terms <- this_res[1:10, ]
        enrichment_dotplot(
          this_selected_terms,
          filename = paste0(
            RESULT_DIR,
            "enrich_plot_top10_down_",
            this_name,
            ".png"
          )
        )
      }
      write.csv(
        enriched_combined$GO_Molecular_Function_2018,
        paste0(RESULT_DIR, "GO_MF_down.csv")
      )
      write.csv(
        enriched_combined$GO_Cellular_Component_2018,
        paste0(RESULT_DIR, "GO_CC_down.csv")
      )
      write.csv(
        enriched_combined$GO_Biological_Process_2018,
        paste0(RESULT_DIR, "GO_BP_down.csv")
      )
      write.csv(enriched_combined$KEGG_2019_Human,
                paste0(RESULT_DIR, "KEGG_down.csv"))
      
       
      }
    }
    
  }
  
      }
    }
    
  
  ## DEG: KO vs KO
  for (i in 7:12) {
    for (j in 7:12) {
      this_1 <- levels(as.factor(this_combined$orig.ident))[j]
      this_2 <- levels(as.factor(this_combined$orig.ident))[i]
      if (this_1 != this_2 &
          !is.na(this_1) & !is.na(this_2) & j > i) {
        RESULT_DIR <-
          paste0("./result/deg/",
                 this_ct,
                 "_positive_",
                 this_1,
                 "_vs_",
                 this_2,
                 "/")
    table1 <- table(this_combined$orig.ident)
    tmp1 <- as.numeric(table1[which(names(table1) == this_1)])
    tmp2 <- as.numeric(table1[which(names(table1) == this_2)])
    
    if (tmp1 > 10 & tmp2 > 10) {
      dir.create(RESULT_DIR, showWarnings = F)
      Idents(this_combined) <- this_combined$orig.ident
      DefaultAssay(this_combined) <- "RNA"
      cts_markers <-
        FindMarkers(this_combined,
                    ident.1 = this_1,
                    ident.2 = this_2) %>%
        rownames_to_column("gene") %>%
        filter(p_val_adj < 0.05)
      
      avg_expr_deg <-
        AverageExpression(this_combined, features = cts_markers$gene)$RNA %>%
        as.data.frame() %>%
        rownames_to_column("gene") %>%
        dplyr::select(gene,`this_1`,`this_2`)

      cts_markers <- cts_markers %>%
        left_join(avg_expr_deg, by="gene") %>%
        arrange(desc(avg_log2FC))
      
      cts_markers %>%
        write_csv(paste0(RESULT_DIR, "deg.csv"))
      
      
       
      library(enrichR)
      dbs <-
        c(
          "GO_Molecular_Function_2018",
          "GO_Cellular_Component_2018",
          "GO_Biological_Process_2018",
          "KEGG_2019_Human"
        )
      
      
      this_up <- cts_markers %>%
        filter(avg_log2FC > 0) %>%
        pull(gene)
      this_down <- cts_markers %>%
        filter(avg_log2FC < 0) %>%
        pull(gene)
      
       # Volcano
      if (length(this_up) > 10 &
          length(this_down) > 10) {
        top_up <- cts_markers %>%
          top_n(10, avg_log2FC) %>%
          pull(gene)
        top_down <- cts_markers %>%
          top_n(-10, avg_log2FC) %>%
          pull(gene)
        
        p1 <- EnhancedVolcano(
          cts_markers,
          lab = cts_markers$gene,
          x = 'avg_log2FC',
          y = 'p_val_adj',
          selectLab = c(top_up, top_down),
          pCutoff = 0.05,
          FCcutoff = 0.25,
        )
        png(
          paste0(RESULT_DIR, "volcano.png"),
          width = 3000,
          height = 3000,
          res = 300
        )
        print(p1)
        dev.off()
        
      }
      
      ### UP
      if (length(this_up) > 10) {
      enriched_combined <- enrichr(this_up, dbs)
      enriched_combined <- lapply(enriched_combined, function(x) {
        x$Overlap <- paste0(" ", x$Overlap)
        return(x[, c(-5, -6)])
      })
      
      for (idx in seq_along(enriched_combined)) {
        this_res <- enriched_combined[[idx]]
        this_name <- names(enriched_combined[idx])
        #this_match_idx <- which(!is.na(str_extract(this_res$Term, keywords)))
        
        ## this_selected_terms <- this_res[1:20, ]
        ## enrichment_dotplot(
        ##   this_selected_terms,
        ##   filename = paste0(RESULT_DIR,
        ##                     "enrich_plot_top20_up_",
        ##                     this_name,
        ##                     ".png")
        ## )
        this_selected_terms <- this_res[1:10, ]
        enrichment_dotplot(
          this_selected_terms,
          filename = paste0(RESULT_DIR,
                            "enrich_plot_top10_up_",
                            this_name,
                            ".png")
        )
      }
      write.csv(
        enriched_combined$GO_Molecular_Function_2018,
        paste0(RESULT_DIR, "GO_MF_up.csv")
      )
      write.csv(
        enriched_combined$GO_Cellular_Component_2018,
        paste0(RESULT_DIR, "GO_CC_up.csv")
      )
      write.csv(
        enriched_combined$GO_Biological_Process_2018,
        paste0(RESULT_DIR, "GO_BP_up.csv")
      )
      write.csv(enriched_combined$KEGG_2019_Human,
                paste0(RESULT_DIR, "KEGG_up.csv"))
      
      }
      ### DOWN
      if (length(this_down) > 10) {
      enriched_combined <- enrichr(this_down, dbs)
      enriched_combined <- lapply(enriched_combined, function(x) {
        x$Overlap <- paste0(" ", x$Overlap)
        return(x[, c(-5, -6)])
      })
      
      for (idx in seq_along(enriched_combined)) {
        this_res <- enriched_combined[[idx]]
        this_name <- names(enriched_combined[idx])
        #this_match_idx <- which(!is.na(str_extract(this_res$Term, keywords)))
        
        ## this_selected_terms <- this_res[1:20, ]
        ## enrichment_dotplot(
        ##   this_selected_terms,
        ##   filename = paste0(
        ##     RESULT_DIR,
        ##     "enrich_plot_top20_down_",
        ##     this_name,
        ##     ".png"
        ##   )
        ## )
        this_selected_terms <- this_res[1:10, ]
        enrichment_dotplot(
          this_selected_terms,
          filename = paste0(
            RESULT_DIR,
            "enrich_plot_top10_down_",
            this_name,
            ".png"
          )
        )
      }
      write.csv(
        enriched_combined$GO_Molecular_Function_2018,
        paste0(RESULT_DIR, "GO_MF_down.csv")
      )
      write.csv(
        enriched_combined$GO_Cellular_Component_2018,
        paste0(RESULT_DIR, "GO_CC_down.csv")
      )
      write.csv(
        enriched_combined$GO_Biological_Process_2018,
        paste0(RESULT_DIR, "GO_BP_down.csv")
      )
      write.csv(enriched_combined$KEGG_2019_Human,
                paste0(RESULT_DIR, "KEGG_down.csv"))
      
       
      }
    }
    
  }
  
      }
    }
    
  #i=6
  ## DEG: KO vs ct
  for (i in 1:6) {
      this_1 <- levels(as.factor(this_combined$orig.ident))[i+6]
      this_2 <- levels(as.factor(this_combined$orig.ident))[i]
      if (this_1 != this_2 &
          !is.na(this_1) & !is.na(this_2)) {
        RESULT_DIR <-
          paste0("./result/deg/",
                 this_ct,
                 "_positive_",
                 this_1,
                 "_vs_",
                 this_2,
                 "/")
    table1 <- table(this_combined$orig.ident)
    tmp1 <- as.numeric(table1[which(names(table1) == this_1)])
    tmp2 <- as.numeric(table1[which(names(table1) == this_2)])
    
    if (tmp1 > 10 & tmp2 > 10) {
      dir.create(RESULT_DIR, showWarnings = F)
      Idents(this_combined) <- this_combined$orig.ident
      DefaultAssay(this_combined) <- "RNA"
      cts_markers <-
        FindMarkers(this_combined,
                    ident.1 = this_1,
                    ident.2 = this_2) %>%
        rownames_to_column("gene") %>%
        filter(p_val_adj < 0.05)
      
      avg_expr_deg <-
        AverageExpression(this_combined, features = cts_markers$gene)$RNA %>%
        as.data.frame() %>%
        rownames_to_column("gene") %>%
        dplyr::select(gene, `this_1`, `this_2`)
      
      cts_markers <- cts_markers %>%
        left_join(avg_expr_deg, by="gene") %>%
        arrange(desc(avg_log2FC))
      
      cts_markers %>%
        write_csv(paste0(RESULT_DIR, "deg.csv"))
      
      library(enrichR)
      dbs <-
        c(
          "GO_Molecular_Function_2018",
          "GO_Cellular_Component_2018",
          "GO_Biological_Process_2018",
          "KEGG_2019_Human"
        )
      
      
      this_up <- cts_markers %>%
        filter(avg_log2FC > 0) %>%
        pull(gene)
      this_down <- cts_markers %>%
        filter(avg_log2FC < 0) %>%
        pull(gene)
      
       # Volcano
      if (length(this_up) > 10 &
          length(this_down) > 10) {
        top_up <- cts_markers %>%
          top_n(10, avg_log2FC) %>%
          pull(gene)
        top_down <- cts_markers %>%
          top_n(-10, avg_log2FC) %>%
          pull(gene)
        
        p1 <- EnhancedVolcano(
          cts_markers,
          lab = cts_markers$gene,
          x = 'avg_log2FC',
          y = 'p_val_adj',
          selectLab = c(top_up, top_down),
          pCutoff = 0.05,
          FCcutoff = 0.25,
        )
        png(
          paste0(RESULT_DIR, "volcano.png"),
          width = 3000,
          height = 3000,
          res = 300
        )
        print(p1)
        dev.off()
        
      }
      
      ### UP
      if (length(this_up) > 10) {
      enriched_combined <- enrichr(this_up, dbs)
      enriched_combined <- lapply(enriched_combined, function(x) {
        x$Overlap <- paste0(" ", x$Overlap)
        return(x[, c(-5, -6)])
      })
      
      for (idx in seq_along(enriched_combined)) {
        this_res <- enriched_combined[[idx]]
        this_name <- names(enriched_combined[idx])
        #this_match_idx <- which(!is.na(str_extract(this_res$Term, keywords)))
        
        ## this_selected_terms <- this_res[1:20, ]
        ## enrichment_dotplot(
        ##   this_selected_terms,
        ##   filename = paste0(RESULT_DIR,
        ##                     "enrich_plot_top20_up_",
        ##                     this_name,
        ##                     ".png")
        ## )
        this_selected_terms <- this_res[1:10, ]
        enrichment_dotplot(
          this_selected_terms,
          filename = paste0(RESULT_DIR,
                            "enrich_plot_top10_up_",
                            this_name,
                            ".png")
        )
      }
      write.csv(
        enriched_combined$GO_Molecular_Function_2018,
        paste0(RESULT_DIR, "GO_MF_up.csv")
      )
      write.csv(
        enriched_combined$GO_Cellular_Component_2018,
        paste0(RESULT_DIR, "GO_CC_up.csv")
      )
      write.csv(
        enriched_combined$GO_Biological_Process_2018,
        paste0(RESULT_DIR, "GO_BP_up.csv")
      )
      write.csv(enriched_combined$KEGG_2019_Human,
                paste0(RESULT_DIR, "KEGG_up.csv"))
      
      }
      ### DOWN
      if (length(this_down) > 10) {
      enriched_combined <- enrichr(this_down, dbs)
      enriched_combined <- lapply(enriched_combined, function(x) {
        x$Overlap <- paste0(" ", x$Overlap)
        return(x[, c(-5, -6)])
      })
      
      for (idx in seq_along(enriched_combined)) {
        this_res <- enriched_combined[[idx]]
        this_name <- names(enriched_combined[idx])
        #this_match_idx <- which(!is.na(str_extract(this_res$Term, keywords)))
        
        ## this_selected_terms <- this_res[1:20, ]
        ## enrichment_dotplot(
        ##   this_selected_terms,
        ##   filename = paste0(
        ##     RESULT_DIR,
        ##     "enrich_plot_top20_down_",
        ##     this_name,
        ##     ".png"
        ##   )
        ## )
        this_selected_terms <- this_res[1:10, ]
        enrichment_dotplot(
          this_selected_terms,
          filename = paste0(
            RESULT_DIR,
            "enrich_plot_top10_down_",
            this_name,
            ".png"
          )
        )
      }
      write.csv(
        enriched_combined$GO_Molecular_Function_2018,
        paste0(RESULT_DIR, "GO_MF_down.csv")
      )
      write.csv(
        enriched_combined$GO_Cellular_Component_2018,
        paste0(RESULT_DIR, "GO_CC_down.csv")
      )
      write.csv(
        enriched_combined$GO_Biological_Process_2018,
        paste0(RESULT_DIR, "GO_BP_down.csv")
      )
      write.csv(enriched_combined$KEGG_2019_Human,
                paste0(RESULT_DIR, "KEGG_down.csv"))
      
       
      }
    }
    
  }
  
      
    }
}


```

# Single marker freq table

```{r,echo=F,eval=F,message=FALSE,warning=F}


DefaultAssay(combined) <- "RNA"
i = 1

Idents(combined) <- combined$orig.ident
for (i in seq_along(unique(provided_marker$gene))) {
  this_marker <- unique(provided_marker$gene)[i]
  this_data <- FetchData(object = combined, vars = this_marker)
  selected_cells <- this_data %>%
    filter(get(this_marker) >  0.1) %>%
    rownames_to_column("cell") %>%
    pull(cell)
  this_obj <- combined[, selected_cells]
  
  combined@meta.data$tmp_ct <-
    ifelse(rownames(combined@meta.data) %in% colnames(this_obj),
           "positive",
           "negative")
  
  p1 <-
    DimPlot(
      combined,
      reduction = "umap",
      group.by = "tmp_ct",
      split.by = "orig.ident",
      cols = custom_color,
      combine = F,
      pt.size = 0.5,
      ncol = 6
    )[[1]] + NoLegend() + ggplot2::theme(legend.position = "top") + ggtitle(this_marker)
  
  
  png(
    paste0(this_marker, "_marker_binary_umap.png"),
    width = 4000,
    height = 1800,
    res = 300
  )
  print(p1)
  dev.off()
  write.csv(table(combined$tmp_ct, combined$orig.ident),
            paste0(this_marker, "_freq.csv"))
}




```


```{r,echo=F,eval=T,message=F,warning=F,error=F}
source("functions.R")
####

#combined <- readRDS("combined.rds")
combined <- qs::qread('combined.qsave')
####

DefaultAssay(combined) <- "RNA"
Idents(combined) <- combined$seurat_clusters
custom_color <-
  as.character(palette36.colors(36)[-2])[1:length(levels(Idents(combined)))]


provided_marker <- read.csv("provided_marker_manual.csv", header = T)


provided_marker$cell_type <- as.factor(provided_marker$cell_type)

Idents(combined) <- combined$orig.ident
DefaultAssay(combined) <- "RNA"
i = 1
j = 1
k = 1
for (i in seq_along(levels(provided_marker$cell_type))) {
  this_ct <- levels(provided_marker$cell_type)[i]
  this_markers <- provided_marker %>%
    filter(cell_type == this_ct) %>%
    pull(gene)
  this_direction <- provided_marker %>%
    filter(cell_type == this_ct) %>%
    pull(direction)
  selected_cells <- vector()
  for (j in seq_along(levels(Idents(combined)))) {
    this_sample <- levels(Idents(combined))[j]
    this_obj <- subset(combined, idents = this_sample)
    mean_expr <-
      as.numeric(AverageExpression(this_obj, features = this_markers)$RNA[, 1])
    this_data <- FetchData(object = this_obj, vars = this_markers)
    
    sample_cells <- rownames(this_data)
    for (k in seq_along(this_markers)) {
      if (this_direction[k] == "pos") {
        this_cells <- this_data %>%
          filter(get(this_markers[k]) >  mean_expr[k]) %>%
          rownames_to_column("cell") %>%
          pull(cell)
        sample_cells <- intersect(sample_cells, this_cells)
      } else{
        this_cells <- this_data %>%
          filter(get(this_markers[k]) <  mean_expr[k]) %>% 
          rownames_to_column("cell") %>%
          pull(cell)
        sample_cells <- intersect(sample_cells, this_cells)
      }
    }
    if(length(sample_cells) > 0) {
      selected_cells <- c(selected_cells, sample_cells)
    }
  }
  selected_cells <- unique(selected_cells)
  this_obj <- combined[,selected_cells]
  
  combined@meta.data$tmp_ct <-
    ifelse(
      rownames(combined@meta.data) %in% colnames(this_obj),
      "positive",
      "negative"
    )
  library(tidyverse)
  
  Idents(combined) <- combined$tmp_ct
  custom_color <- c('#C0C0C0', '#B00D23')

  p1 <-
    DimPlot(
      combined,
      reduction = "umap",
      group.by = "tmp_ct",
      split.by = "orig.ident",
      cols = custom_color,
      combine = F,
      pt.size = 0.5,
      ncol = 6
    )[[1]] + NoLegend() + ggplot2::theme(legend.position = "top") + ggtitle(this_ct)
  
  
  png(
    paste0(this_ct, "_marker_umap.png"),
    width = 4000,
    height = 1800,
    res = 300
  )
  print(p1)
  dev.off()
  
  # for (i in seq_along(this_markers)) {
  #   p1 <-
  #     FeaturePlot(
  #       combined,
  #       as.character(this_markers[i]),
  #       split.by = "orig.ident",
  #       combine = F,
  #       pt.size = 0.25,
  #       keep.scale = "all",
  #       cols = c('#C0C0C0', '#B00D23') # From Apple (PRODUCT)RED
  #     )
  #   
  #   p2 <- lapply(p1, function(x) {
  #     x + theme(
  #       axis.text.x = element_blank(),
  #       axis.text.y = element_blank(),
  #       axis.title.x = element_blank(),
  #       axis.title.y = element_blank(),
  #       axis.ticks.x = element_blank(),
  #       axis.ticks.y = element_blank()
  #     )
  #   })
  #   
  #   p3 <- CombinePlots(p2, ncol = 6, legend = "right")
  #   
  #   png(
  #     paste(
  #       this_ct,
  #       "_",
  #       as.character(this_markers[i]),
  #       "_umap.png",
  #       sep = ""
  #     ),
  #     width = 6000,
  #     height = 1800,
  #     res = 300
  #   )
  #   print(p3)
  #   dev.off()
  # }
  
}


```
