---
title: "Cell type annotation"
author: "Cankun Wang"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Seurat)
library(cowplot)
library(dplyr)
library(ggplot2)
library(patchwork)
library(here)
library(qs)
library(Polychrome)
library(RColorBrewer)
library(tidyverse)
library(fgsea)
library(msigdbr)
library(monocle3)
library(batchelor)
library(Matrix.utils)
#BiocManager::install(c('batchelor', 'Matrix.utils'))
```


# Set working dir

```{r,echo=F,eval=T,message=F,warning=F,error=F}
here::i_am("5.Rmd")
here::set_here()
print(paste("Current working directory:", here::here()))

```

# Load data

```{r,echo=F,eval=T,message=F,warning=F,error=F}
source("functions.R")
####

#combined <- readRDS("combined.rds")
combined <- qs::qread('combined.qsave')
####

DefaultAssay(combined) <- "RNA"
Idents(combined) <- combined$seurat_clusters
custom_color <-
  as.character(palette36.colors(36)[-2])[1:length(levels(Idents(combined)))]


provided_marker <- read.csv("provided_marker_manual.csv", header = T)


provided_marker$cell_type <- as.factor(provided_marker$cell_type)

Idents(combined) <- combined$orig.ident
DefaultAssay(combined) <- "RNA"
i = 1
j = 1
k = 1
idx = 1
```

# DEG

```{r,echo=F,eval=F,message=FALSE,warning=F}
dir.create('result')
dir.create('result/cell_type')
dir.create('result/deg')

Idents(combined) <- combined$orig.ident

table(combined$seurat_clusters)
empty_category <- as.factor(combined$orig.ident)
levels(empty_category) <-
  rep("empty_category", length(levels(empty_category)))
combined <-
  AddMetaData(combined, metadata = empty_category, col.name = "empty_category")



Idents(combined) <- combined$empty_category
DefaultAssay(combined) <- "RNA"
i = 1
j = 1
k = 1

for (idx in seq_along(levels(provided_marker$cell_type))) {
  print(idx)
  this_ct <- levels(provided_marker$cell_type)[idx]
  this_markers <- provided_marker %>%
    filter(cell_type == this_ct) %>%
    pull(gene)
  this_direction <- provided_marker %>%
    filter(cell_type == this_ct) %>%
    pull(direction)
  this_data <- FetchData(object = combined, vars = this_markers)
  selected_cells <- rownames(this_data)
  for (k in seq_along(this_markers)) {
    if (this_direction[k] == "pos") {
      this_cells <- this_data %>%
        filter(get(this_markers[k]) >  0.1) %>%
        rownames_to_column("cell") %>%
        pull(cell)
      selected_cells <- intersect(selected_cells, this_cells)
    } else{
      this_cells <- this_data %>%
        filter(get(this_markers[k]) <= 0) %>%
        rownames_to_column("cell") %>%
        pull(cell)
      selected_cells <- intersect(selected_cells, this_cells)
    }
  }
  
  selected_cells <- unique(selected_cells)
  this_obj <- combined[, selected_cells]
  
  combined@meta.data$tmp_ct <-
    ifelse(rownames(combined@meta.data) %in% colnames(this_obj),
           "positive",
           "negative")
  library(tidyverse)
  
  Idents(combined) <- combined$tmp_ct
  custom_color <- c('#C0C0C0', '#B00D23')
  
  # DEG
  Idents(combined) <- combined$orig.ident
  
  j = levels(as.factor(combined$orig.ident))[6]
  for (j in levels(as.factor(combined$orig.ident))) {
    this_1 <- levels(as.factor(combined$tmp_ct))[2]
    this_2 <- levels(as.factor(combined$tmp_ct))[1]
    this_sample <- j
    
    this_combined <- subset(combined, idents = this_sample)
    RESULT_DIR <-
      paste0("./result/deg/",
             this_sample,
             "_",
             this_ct,
             "_",
             this_1,
             "_vs_",
             this_2,
             "/")
    
    if (length(levels(as.factor(this_combined$tmp_ct))) > 1 &
        all(table(this_combined$tmp_ct) > 5)) {
      dir.create(RESULT_DIR, showWarnings = F)
      Idents(this_combined) <- this_combined$tmp_ct
      DefaultAssay(this_combined) <- "RNA"
      cts_markers <-
        FindMarkers(
          this_combined,
          ident.1 = this_1,
          ident.2 = this_2,
          logfc.threshold = 0,
          verbose = F
        ) %>%
        rownames_to_column("gene")
      
      avg_expr_deg <-
        AverageExpression(this_combined, features = cts_markers$gene)$RNA %>%
        as.data.frame() %>%
        rownames_to_column("gene") %>%
        dplyr::rename(group1_expr = positive, group2_expr = negative)
      
      cts_markers <- cts_markers %>%
        left_join(avg_expr_deg, by = "gene") %>%
        arrange(desc(avg_log2FC))
      
      cts_markers %>%
        write_csv(paste0(RESULT_DIR, "deg_full.csv"))
    }
  }
  
  
  Idents(combined) <- combined$tmp_ct
  this_positive <- levels(Idents(combined))[2]
  this_combined <- subset(combined, idents = this_positive)
  Idents(this_combined) <- this_combined$orig.ident
  ## DEG: con vs con
  idx = 1
  i = 5
  j = 6
  for (i in 1:6) {
    for (j in 1:6) {
      this_1 <- levels(as.factor(this_combined$orig.ident))[j]
      this_2 <- levels(as.factor(this_combined$orig.ident))[i]
      if (this_1 != this_2 &
          !is.na(this_1) & !is.na(this_2) & j > i) {
        RESULT_DIR <-
          paste0("./result/deg/",
                 this_ct,
                 "_positive_",
                 this_1,
                 "_vs_",
                 this_2,
                 "/")
        table1 <- table(this_combined$orig.ident)
        tmp1 <- as.numeric(table1[which(names(table1) == this_1)])
        tmp2 <- as.numeric(table1[which(names(table1) == this_2)])
        
        if (tmp1 > 10 & tmp2 > 10) {
          dir.create(RESULT_DIR, showWarnings = F)
          Idents(this_combined) <- this_combined$orig.ident
          DefaultAssay(this_combined) <- "RNA"
          cts_markers <-
            FindMarkers(
              this_combined,
              ident.1 = this_1,
              ident.2 = this_2,
              logfc.threshold = 0,
              verbose = F
            ) %>%
            rownames_to_column("gene")
          
          avg_expr_deg <-
            AverageExpression(this_combined, features = cts_markers$gene)$RNA %>%
            as.data.frame() %>%
            rownames_to_column("gene") %>%
            dplyr::select(gene, `this_1`, `this_2`)
          
          cts_markers <- cts_markers %>%
            left_join(avg_expr_deg, by = "gene") %>%
            arrange(desc(avg_log2FC))
          cts_markers %>%
            write_csv(paste0(RESULT_DIR, "deg_full.csv"))
        }
      }
    }
  }
  
  
  
  ## DEG: KO vs KO
  for (i in 7:12) {
    for (j in 7:12) {
      this_1 <- levels(as.factor(this_combined$orig.ident))[j]
      this_2 <- levels(as.factor(this_combined$orig.ident))[i]
      if (this_1 != this_2 &
          !is.na(this_1) & !is.na(this_2) & j > i) {
        RESULT_DIR <-
          paste0("./result/deg/",
                 this_ct,
                 "_positive_",
                 this_1,
                 "_vs_",
                 this_2,
                 "/")
        table1 <- table(this_combined$orig.ident)
        tmp1 <- as.numeric(table1[which(names(table1) == this_1)])
        tmp2 <- as.numeric(table1[which(names(table1) == this_2)])
        
        if (tmp1 > 10 & tmp2 > 10) {
          dir.create(RESULT_DIR, showWarnings = F)
          Idents(this_combined) <- this_combined$orig.ident
          DefaultAssay(this_combined) <- "RNA"
          cts_markers <-
            FindMarkers(
              this_combined,
              ident.1 = this_1,
              ident.2 = this_2,
              logfc.threshold = 0,
              verbose = F
            ) %>%
            rownames_to_column("gene")
          
          avg_expr_deg <-
            AverageExpression(this_combined, features = cts_markers$gene)$RNA %>%
            as.data.frame() %>%
            rownames_to_column("gene") %>%
            dplyr::select(gene, `this_1`, `this_2`)
          
          cts_markers <- cts_markers %>%
            left_join(avg_expr_deg, by = "gene") %>%
            arrange(desc(avg_log2FC))
          
          cts_markers %>%
            write_csv(paste0(RESULT_DIR, "deg_full.csv"))
          
        }
      }
    }
  }
  
  
  ## DEG: KO vs ct
  for (i in 1:6) {
    this_1 <- levels(as.factor(this_combined$orig.ident))[i + 6]
    this_2 <- levels(as.factor(this_combined$orig.ident))[i]
    if (this_1 != this_2 &
        !is.na(this_1) & !is.na(this_2)) {
      RESULT_DIR <-
        paste0("./result/deg/",
               this_ct,
               "_positive_",
               this_1,
               "_vs_",
               this_2,
               "/")
      table1 <- table(this_combined$orig.ident)
      tmp1 <- as.numeric(table1[which(names(table1) == this_1)])
      tmp2 <- as.numeric(table1[which(names(table1) == this_2)])
      
      if (tmp1 > 10 & tmp2 > 10) {
        dir.create(RESULT_DIR, showWarnings = F)
        Idents(this_combined) <- this_combined$orig.ident
        DefaultAssay(this_combined) <- "RNA"
        cts_markers <-
          FindMarkers(
            this_combined,
            ident.1 = this_1,
            ident.2 = this_2,
            logfc.threshold = 0,
            verbose = F
          ) %>%
          rownames_to_column("gene")
        
        avg_expr_deg <-
          AverageExpression(this_combined, features = cts_markers$gene)$RNA %>%
          as.data.frame() %>%
          rownames_to_column("gene") %>%
          dplyr::select(gene, `this_1`, `this_2`)
        
        cts_markers <- cts_markers %>%
          left_join(avg_expr_deg, by = "gene") %>%
          arrange(desc(avg_log2FC))
        
        cts_markers %>%
          write_csv(paste0(RESULT_DIR, "deg_full.csv"))
        
        
      }
    }
  }
}
```
