---
title: "Subpopulation analysis by sample"
author: "Cankun Wang"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Seurat)
library(cowplot)
library(dplyr)
library(ggplot2)
library(patchwork)
library(here)
library(qs)
library(Polychrome)
library(RColorBrewer)
library(tidyverse)
library(fgsea)
library(monocle3)
library(batchelor)
library(Matrix.utils)
library(tidyverse)
library(SeuratWrappers)
library(enrichR)
library(dittoSeq)
```


# Set working dir

```{r,echo=F,eval=T,message=F,warning=F,error=F}
here::i_am("9_subpopulation_analysis_by_sample.rmd")
here::set_here()
print(paste("Current working directory:", here::here()))

```

# Load data

```{r,echo=F,eval=T,message=F,warning=F,error=F}
source("functions.R")

combined <- qs::qread('combined.qsave')
#qs::qsave(combined, 'combined.qsave')
DefaultAssay(combined) <- "RNA"
Idents(combined) <- combined$seurat_clusters
#custom_color <-
#  as.character(palette36.colors(36)[-2])[1:length(levels(Idents(combined)))]

custom_color <-
  as.character(Polychrome::glasbey.colors()[-1])

two_color <- c('#C0C0C0', '#B00D23')

provided_marker <- read.csv("provided_marker_manual.csv", header = T)
provided_marker$cell_type <- as.factor(provided_marker$cell_type)

Idents(combined) <- combined$orig.ident
DefaultAssay(combined) <- "RNA"


i = 1
j = 1
k = 1
idx = 1


days <- levels(combined$orig.ident)


dbs <-
  c(
    "GO_Molecular_Function_2018",
    "GO_Cellular_Component_2018",
    "GO_Biological_Process_2018",
    "KEGG_2019_Human"
  )
  
```


# Subset 

```{r,echo=F,eval=F,message=FALSE,warning=F}
dir.create('result')
dir.create('result/subpopulation')

Idents(combined) <- combined$orig.ident
DefaultAssay(combined) <- "RNA"

# seq_along(levels(provided_marker$cell_type))
day <- days[[2]]
for (day in days) {
  RESULT_DIR <-
    paste0("./result/subpopulation/",
           day,
           "/")
  dir.create(RESULT_DIR)
  dir.create(paste0(RESULT_DIR, "/umap"))
  #dir.create(paste0(RESULT_DIR, "/deg"))
  #dir.create(paste0(RESULT_DIR, "/cell_proportion"))
  dir.create(paste0(RESULT_DIR, "/marker"))
  
  Idents(combined) <- combined$orig.ident
  
  
  sub_combined <- subset(combined, idents = day)
  Idents(sub_combined) <- sub_combined$orig.ident
  #DimPlot(sub_combined, reduction = 'umap')
  
  DefaultAssay(sub_combined) <- "integrated"
  sub_combined <- RunPCA(sub_combined, npcs = 20, verbose = FALSE)
  sub_combined <-
    RunUMAP(sub_combined, reduction = "pca", dims = 1:10)
  sub_combined <-
    FindNeighbors(sub_combined, reduction = "pca", dims = 1:10)
  sub_combined <- FindClusters(sub_combined, resolution = 0.2)
  DefaultAssay(sub_combined) <- "RNA"
  #sub_combined <- ScaleData(sub_combined, verbose = FALSE)
  
  Idents(sub_combined) <- sub_combined$tmp_ct
  p1 <-
    DimPlot(sub_combined, reduction = 'umap', cols = custom_color)
  
  png(
    paste(RESULT_DIR, "umap/combined_cell_type.png",
          sep = ""),
    width = 2500,
    height = 1500,
    res = 300
  )
  print(p1)
  dev.off()
  
  Idents(sub_combined) <- sub_combined$seurat_clusters
  
  p1 <-
    DimPlot(sub_combined, reduction = 'umap', cols = custom_color)
  
  png(
    paste(RESULT_DIR, "umap/cluster.png",
          sep = ""),
    width = 1800,
    height = 1500,
    res = 300
  )
  print(p1)
  dev.off()
  #idx=7
  for (idx in seq_along(levels(provided_marker$cell_type))) {
    this_ct <- levels(provided_marker$cell_type)[idx]
    this_ct_ident <- gsub(" ", "_", this_ct)
    this_ct_index <-
      which(colnames(combined@meta.data) == this_ct_ident)
    Idents(sub_combined) <-
      as.factor(sub_combined@meta.data[, this_ct_index])
    # Re-arrange levels if needed
    #if(levels(Idents(sub_combined))[1] == 'positive') {
    #  sub_combined@meta.data[this_ct_index] <- factor(, levels = c("negative", "positive"))
    #}
    
    p1 <-
      DimPlot(sub_combined, reduction = 'umap', cols = two_color) + ggtitle(this_ct)
    
    png(
      paste(RESULT_DIR, "umap/", this_ct_ident, ".png",
            sep = ""),
      width = 1800,
      height = 1500,
      res = 300
    )
    print(p1)
    dev.off()
  }
  
  # Marker gene UMAP plot
  for (i in seq_along(provided_marker$gene)) {
    this_gene <- provided_marker$gene[i]
    this_ct <- as.character(provided_marker$cell_type[i])
    p1 <-
      FeaturePlot(sub_combined,
                  this_gene,
                  pt.size = 0.4,
                  cols = two_color)
    
    png(
      paste(
        RESULT_DIR,
        "marker/",
        this_gene,
        "_",
        this_ct,
        "_umap.png",
        sep = ""
      ),
      width = 2000,
      height = 1800,
      res = 300
    )
    print(p1)
    dev.off()
  }
  
  # Cluster_specific
  
  #Idents(sub_combined) <- sub_combined$seurat_clusters
  #this_markers <-
  #  FindAllMarkers(sub_combined) %>%
  #  rownames_to_column("gene") %>%
  #  filter(p_val_adj < 0.05)
  
  # Cell proportion
  #p1 <-
  #  dittoBarPlot(
  #    sub_combined,
  #    "orig.ident",
  #    group.by = "seurat_clusters",
  #    xlab = "Cluster",
  #    scale = "percent",
  #    main = '',
  #    color.panel =  custom_color
  #  )
  #
  #png(
  #  paste0(RESULT_DIR,'/cell_proportion/', day[3], "_proportion_pct.png"),
  #  width = 2000,
  #  height = 2000,
  #  res = 300
  #)
  #print(p1)
  #dev.off()
  #
  #p2 <-
  #  dittoBarPlot(
  #    sub_combined,
  #    "orig.ident",
  #    group.by = "seurat_clusters",
  #    xlab = "Cluster",
  #    scale = "count",
  #    main = '',
  #    color.panel =  custom_color
  #  )
  #
  #png(
  #  paste0(RESULT_DIR,'/cell_proportion/', day[3], "_proportion_count.png"),
  #  width = 2000,
  #  height = 2000,
  #  res = 300
  #)
  #print(p2)
  #dev.off()
  
  ## DEG
  #Idents(sub_combined) <- sub_combined$orig.ident
  #DefaultAssay(sub_combined) <- "RNA"
  #this_cluster_idx <- 8
  #for (this_cluster_idx in seq_along(levels(as.factor(sub_combined$seurat_clusters)))) {
  #  this_cluster <- levels(as.factor(sub_combined$seurat_clusters))[this_cluster_idx]
  #  Idents(sub_combined) <- sub_combined$seurat_clusters
  #  this_combined <- subset(sub_combined, idents = this_cluster)
  #  ident_freq <- as.numeric(table(as.character(this_combined$orig.ident)))
  #  if(all(ident_freq > 5) & length(ident_freq) > 1) {
  #    Idents(this_combined) <- this_combined$orig.ident
  #    this_markers <-
  #      FindMarkers(this_combined,
  #                  ident.1 = day[2],
  #                  ident.2 = day[1]) %>%
  #      rownames_to_column("gene") %>%
  #      filter(p_val_adj < 0.05)
  #
  #  avg_expr_deg <-
  #    AverageExpression(this_combined, features = this_markers$gene)$RNA %>%
  #    as.data.frame() %>%
  #    rownames_to_column("gene")
  #
  #  this_markers <- this_markers %>%
  #    left_join(avg_expr_deg, by = "gene") %>%
  #    arrange(desc(avg_log2FC))
  #
  #  this_markers %>%
  #    write_csv(paste0(RESULT_DIR, "/deg/cluster",this_cluster,"_KO_vs_Con.csv"))
  #
  #
  #
  #  this_up <- this_markers %>%
  #    filter(avg_log2FC > 0) %>%
  #    pull(gene)
  #  this_down <- this_markers %>%
  #    filter(avg_log2FC < 0) %>%
  #    pull(gene)
  #
  #
  #    ### UP
  #    enriched_combined <- enrichr(this_up, dbs)
  #    enriched_combined <- lapply(enriched_combined, function(x) {
  #      if (nrow(x) > 0) {
  #        x$Overlap <- paste0(" ", x$Overlap)
  #        return(x[, c(-5,-6)])
  #      } else{
  #        return(x)
  #      }
  #    })
  #
  #    write.csv(
  #      enriched_combined$GO_Molecular_Function_2018,
  #      paste0(RESULT_DIR, "/deg/cluster",this_cluster,"_GO_MF_up.csv")
  #    )
  #    write.csv(
  #      enriched_combined$GO_Cellular_Component_2018,
  #      paste0(RESULT_DIR, "/deg/cluster",this_cluster, "_GO_CC_up.csv")
  #    )
  #    write.csv(
  #      enriched_combined$GO_Biological_Process_2018,
  #      paste0(RESULT_DIR, "/deg/cluster",this_cluster, "_GO_BP_up.csv")
  #    )
  #    write.csv(enriched_combined$KEGG_2019_Human,
  #              paste0(RESULT_DIR, "/deg/cluster",this_cluster, "_KEGG_up.csv"))
  #
  #    ### DOWN
  #    enriched_combined <- enrichr(this_down, dbs)
  #    enriched_combined <- lapply(enriched_combined, function(x) {
  #      if (nrow(x) > 0) {
  #        x$Overlap <- paste0(" ", x$Overlap)
  #        return(x[, c(-5,-6)])
  #      } else{
  #        return(x)
  #      }
  #    })
  #
  #    write.csv(
  #      enriched_combined$GO_Molecular_Function_2018,
  #      paste0(RESULT_DIR, "/deg/cluster",this_cluster, "_GO_MF_down.csv")
  #    )
  #    write.csv(
  #      enriched_combined$GO_Cellular_Component_2018,
  #      paste0(RESULT_DIR, "/deg/cluster",this_cluster, "_GO_CC_down.csv")
  #    )
  #    write.csv(
  #      enriched_combined$GO_Biological_Process_2018,
  #      paste0(RESULT_DIR, "/deg/cluster",this_cluster, "_GO_BP_down.csv")
  #    )
  #    write.csv(enriched_combined$KEGG_2019_Human,
  #              paste0(RESULT_DIR, "/deg/cluster",this_cluster, "_KEGG_down.csv"))
  #  }
  #
  #}
}


```

```{r,echo=F,eval=F,message=FALSE,warning=F}




```





```{r}

```


