---
title: "3. Data integration"
author: "Cankun Wang"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(error = FALSE)
library(Seurat)
library(cowplot)
library(dplyr)
library(ggplot2)
library(patchwork)
library(here)
library(qs)
library(Polychrome)
library(harmony)
```


# Set working dir

```{r,echo=F,eval=T,message=F,warning=F,error=F}

here::i_am("integration_day.rmd")
here::set_here()
print(paste("Current working directory:", here::here()))

```

# Load data

```{r,echo=F,eval=T,message=F,warning=F,error=F}

combined <- qs::qread('combined.qsave')
```

# Dimension reduction

```{r}
# Harmony integration method
days <- c("0", "2", "5", "10", "14", "30")
combine.list <- SplitObject(combined, split.by = "orig.ident")

i = 30

for(i in days) {
  this_days <- c(paste0("Con", i), paste0("N1KO", i))
  sample_idx <- which(names(combine.list) %in% this_days)
  sub_list <- combine.list[sample_idx]
  sub_combined <-
    merge(sub_list[[1]], sub_list[[2]])
  DefaultAssay(sub_combined) <- "RNA"
  sub_combined <- ScaleData(sub_combined, verbose = FALSE)
  sub_combined <- FindVariableFeatures(sub_combined, selection.method = "vst", nfeatures = 2000) 
  sub_combined <- RunPCA(sub_combined, pc.genes = sub_combined@var.genes, npcs = 20, verbose = FALSE)
  sub_combined <- RunHarmony(sub_combined, "orig.ident", plot_convergence = TRUE)
  sub_combined <-
    RunUMAP(sub_combined, reduction = "harmony", dims = 1:20)
  sub_combined <-
    FindNeighbors(sub_combined, reduction = "pca", dims = 1:20)
  sub_combined <- FindClusters(sub_combined, resolution = 0.2)
  
  Idents(combined) <- combined$orig.ident
  this_combind <- subset(combined, idents = this_days)
  sub_combined <-
    AddMetaData(sub_combined, this_combind$cell_type, col.name = "cell_type")
  qs::qsave(sub_combined, paste0("../integration/day", i, "_harmony.qsave"))
}

```


```{r,echo=F,eval=T,message=F,warning=F,error=F}
# Seurat integration method
days <- c("0", "2", "5", "10", "14", "30")

i = 30
for(i in days) {
  this_days <- c(paste0("Con", i), paste0("N1KO", i))
  sample_idx <- which(names(combine.list) %in% this_days)
  sub_list <- combine.list[sample_idx]
  combine.anchors <-
    FindIntegrationAnchors(object.list = sub_list, dims = 1:20)
  sub_combined <-
    IntegrateData(anchorset = combine.anchors, dims = 1:20)
  DefaultAssay(sub_combined) <- "integrated"
  sub_combined <- ScaleData(sub_combined, verbose = FALSE)
  sub_combined <- RunPCA(sub_combined, npcs = 20, verbose = FALSE)
  sub_combined <-
    RunUMAP(sub_combined, reduction = "pca", dims = 1:20)
  sub_combined <-
    FindNeighbors(sub_combined, reduction = "pca", dims = 1:20)
  sub_combined <- FindClusters(sub_combined, resolution = 0.4)
  
  Idents(combined) <- combined$orig.ident
  this_combind <- subset(combined, idents = this_days)
  sub_combined <-
    AddMetaData(sub_combined, this_combind$cell_type, col.name = "cell_type")
  qs::qsave(sub_combined, paste0("../integration/day", i, ".qsave"))
}

```

# All controls (deprecated)

```{r,echo=F,eval=T,message=F,warning=F,error=F}

sub_combined <-
  subset(combined,
         idents = c("Con0", "Con2", "Con5", "Con10", "Con14", "Con30"))
DefaultAssay(sub_combined) <- "RNA"
sub_combined <- ScaleData(sub_combined, verbose = FALSE)
sub_combined <-
  FindVariableFeatures(sub_combined,
                       selection.method = "vst",
                       nfeatures = 2000)
sub_combined <-
  RunPCA(
    sub_combined,
    pc.genes = sub_combined@var.genes,
    npcs = 20,
    verbose = FALSE
  )
sub_combined <-
  RunHarmony(sub_combined, "orig.ident", plot_convergence = TRUE)
sub_combined <-
  RunUMAP(sub_combined, reduction = "harmony", dims = 1:20)
sub_combined <-
  FindNeighbors(sub_combined, reduction = "pca", dims = 1:20)
sub_combined <- FindClusters(sub_combined, resolution = 0.2)

this_combind <- subset(combined, cells = colnames(sub_combined))

sub_combined <-
  AddMetaData(sub_combined, this_combind$cell_type, col.name = "cell_type")
qs::qsave(sub_combined, paste0("../integration/con_harmony.qsave"))


```


# All KO (deprecated)

```{r,echo=F,eval=T,message=F,warning=F,error=F}

sub_combined <-
  subset(combined,
         idents = c("N1KO0", "N1KO2", "N1KO5", "N1KO10", "N1KO14", "N1KO30"))
DefaultAssay(sub_combined) <- "RNA"
sub_combined <- ScaleData(sub_combined, verbose = FALSE)
sub_combined <-
  FindVariableFeatures(sub_combined,
                       selection.method = "vst",
                       nfeatures = 2000)
sub_combined <-
  RunPCA(
    sub_combined,
    pc.genes = sub_combined@var.genes,
    npcs = 20,
    verbose = FALSE
  )
sub_combined <-
  RunHarmony(sub_combined, "orig.ident", plot_convergence = TRUE)
sub_combined <-
  RunUMAP(sub_combined, reduction = "harmony", dims = 1:20)
sub_combined <-
  FindNeighbors(sub_combined, reduction = "pca", dims = 1:20)
sub_combined <- FindClusters(sub_combined, resolution = 0.2)

this_combind <- subset(combined, cells = colnames(sub_combined))
sub_combined <-
  AddMetaData(sub_combined, this_combind$cell_type, col.name = "cell_type")
qs::qsave(sub_combined, paste0("../integration/ko_harmony.qsave"))


```


# All samples (deprecated)

```{r,echo=F,eval=T,message=F,warning=F,error=F}

sub_combined <- combined
DefaultAssay(sub_combined) <- "RNA"
sub_combined <- ScaleData(sub_combined, verbose = FALSE)
sub_combined <-
  FindVariableFeatures(sub_combined,
                       selection.method = "vst",
                       nfeatures = 2000)
sub_combined <-
  RunPCA(
    sub_combined,
    pc.genes = sub_combined@var.genes,
    npcs = 20,
    verbose = FALSE
  )
sub_combined <-
  RunHarmony(sub_combined, "orig.ident", plot_convergence = TRUE)
sub_combined <-
  RunUMAP(sub_combined, reduction = "harmony", dims = 1:20)
sub_combined <-
  FindNeighbors(sub_combined, reduction = "pca", dims = 1:20)
sub_combined <- FindClusters(sub_combined, resolution = 0.2)

sub_combined <-
  AddMetaData(sub_combined, combined$cell_type, col.name = "cell_type")
qs::qsave(sub_combined, paste0("../integration/all_harmony.qsave"))


```


```{r,echo=F,eval=F,message=F,warning=F,error=F, fig.width=12}
sub_combined <- qs::qread("../integration/day30_harmony.qsave")

DimPlot(
  sub_combined,
  reduction = "umap",
  cols = cell_type_color,
  label = T
)

DimPlot(
  sub_combined,
  reduction = "umap",
  group.by = "orig.ident",
  cols = cell_type_color,
  label = T
)

DimPlot(
  sub_combined,
  reduction = "umap",
  group.by = "cell_type",
  cols = cell_type_color,
  label = T
)

DimPlot(
  sub_combined,
  reduction = "umap",
  group.by = "cell_type",
  split.by = "orig.ident",
  cols = cell_type_color,
  label = T,
  ncol = 6
)

```

```{r, fig.width=12}

FeaturePlot(sub_combined, features = c("TNNT2","POU5F1","MYH7","ACTA2","MYH11"), ncol = 3)

```



```{r,echo=F,eval=F,message=F,warning=F,error=F, fig.width=12}
sub_combined <- qs::qread("../integration/day14_harmony.qsave")
DimPlot(
  sub_combined,
  reduction = "umap",
  cols = cell_type_color,
  label = T
)

DimPlot(
  sub_combined,
  reduction = "umap",
  group.by = "orig.ident",
  cols = cell_type_color,
  label = T
)

DimPlot(
  sub_combined,
  reduction = "umap",
  group.by = "cell_type",
  cols = cell_type_color,
  label = T
)

DimPlot(
  sub_combined,
  reduction = "umap",
  group.by = "cell_type",
  split.by = "orig.ident",
  cols = cell_type_color,
  label = T
)

DimPlot(
  sub_combined,
  reduction = "umap",
  group.by = "seurat_clusters",
  cols = cell_type_color,
  label = T
)

DimPlot(
  sub_combined,
  reduction = "umap",
  group.by = "seurat_clusters",
  split.by = "orig.ident",
  cols = cell_type_color,
  label = T
)

p1 <- FeaturePlot(
  this_combined,
  features  = "TNNT2",
  split.by = "orig.ident",
  label = T
)


```


```{r, fig.width=12}

DimPlot(
  sub_combined,
  reduction = "umap",
  group.by = "cell_type",
  split.by = "orig.ident",
  cols = cell_type_color,
  label = T
)

```


```{r, fig.width=8, fig.height = 18}
this_day <- "day30"
 this_markers <- provided_marker %>%
  filter(str_detect(day, this_day)) %>%
  pull(gene)

sub_combined <- qs::qread("../integration/day30_harmony.qsave")
FeaturePlot(
  sub_combined,
  features = c("TNNT2","MYH11","ACTA2","MYL2","MYH6","MYH7","NR2F2"),
  ncol = 3,
  keep.scale = NULL,
  split.by = "orig.ident",
  pt.size = 0.4
) & theme(legend.position = "left")

```



```{r,echo=F,eval=T,message=FALSE,warning=F}
# Re-order the time 
combined$orig.ident <- factor(combined$orig.ident, levels = levels(as.factor(combined$orig.ident))[c(1,4,6,2,3,5,7,10,12,8,9,11)])
qs::qsave(combined, "combined.qsave") 

```

# Session info

```{r,echo=F,eval=T,message=F,warning=F}
sessionInfo()
```
