---
title: "Generate marker gene table"
author: "Cankun Wang"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
library(tidyverse)

knitr::opts_knit$set(root.dir = "D:/Project/BISR/marker")

setwd("D:/Project/BISR/marker")
```


# Background

- CellMarker: http://biocc.hrbmu.edu.cn/CellMarker/
- CellMatch: https://github.com/ZJUFanLab/scCATCH
- PanglaoDB: https://panglaodb.se/

```{r,echo=F,eval=T,message=F,warning=F,error=F}

TISSUE <- "Heart"
SPECIES <- "Human"

ORGAN_PANLAODB <- "Heart"


```

```{r,echo=F,eval=T,message=F,warning=F,error=F}
cellmarker_db_raw <-
  vroom::vroom(paste0("http://bio-bigdata.hrbmu.edu.cn/CellMarker/download/",SPECIES,"_cell_markers.txt"))
cellmatch_raw <- read_rds("cellmatch.rds")

panglaodb_raw <- read_tsv("PanglaoDB_markers_27_Mar_2020.tsv")


```

```{r,echo=F,eval=T,message=F,warning=F,error=F}

cell_markers <- cellmarker_db_raw %>%
  dplyr::filter(tissueType == TISSUE) %>%
  mutate(geneSymbol = str_replace_all(geneSymbol, "\\[|\\]", "")) %>%
  dplyr::select(cellName, geneSymbol) %>%
  tidyr::separate_rows(geneSymbol, sep=", ") %>%
  dplyr::rename(cell_type = cellName, symbol = geneSymbol)

```

```{r,echo=F,eval=F,message=F,warning=F,error=F}

cellmatch_tissues <- cellmatch_raw %>%
  filter(speciesType == SPECIES) %>%
  pull(tissueType) %>%
  unique()

cellmatch <- cellmatch_raw %>%
  filter(speciesType == SPECIES & tissueType == TISSUE) %>%
  dplyr::select(cellName, geneSymbol) %>%
  dplyr::rename(cell_type = cellName, symbol = geneSymbol)


```


```{r,echo=F,eval=F,message=F,warning=F,error=F}

panlao <- panglaodb_raw %>%
  filter(organ == ORGAN_PANLAODB) %>%
  dplyr::rename(cell_type = `cell type`, symbol = `official gene symbol`) %>%
  group_by(cell_type) %>%
  arrange(desc(sensitivity_mouse)) %>%
  top_n(20) %>%
  dplyr::select(cell_type, symbol)
  
```

```{r,echo=F,eval=F,message=F,warning=F,error=F}
# Combine all 3 database


#remotes::install_gitlab("hrbrmstr/pluralize")
library(pluralize)

# convert plural to singular
result_marker <- cell_markers %>%
  bind_rows(cellmatch) %>%
  bind_rows(panlao) %>%
  mutate(
    cell_type = singularize(.$cell_type)
  ) %>%
  mutate(symbol = str_replace_all(symbol, "\\[|\\]", "")) %>%
  filter(symbol != "NA") %>%
  unique() %>%
  write_csv("mingtao_notch1_marker.csv")

 
result_marker %>%
  group_by(cell_type) %>%
  mutate(idx = row_number()) %>% 
  mutate(symbol = toupper(symbol)) %>%
  tidyr::spread(cell_type,symbol) %>%
  dplyr::select(-idx) %>%
  write_csv("mingtao_notch1_marker_SCINA.csv")
  


```

```{r,echo=F,eval=F,message=F,warning=F,error=F}

# Save CellMarker DB to SCINA and human-readable format
cell_markers_save <- cellmarker_db_raw %>%
  filter(tissueType == TISSUE) %>%
  mutate(geneSymbol = str_replace_all(geneSymbol, "\\[|\\]", "")) %>%
  dplyr::select(cellName, geneSymbol) %>%
  tidyr::separate_rows(geneSymbol, sep=", ") %>%
  dplyr::rename(cell_type = cellName, symbol = geneSymbol) %>%
  group_by(cell_type) %>%
  filter(!symbol == "NA") %>%
  drop_na() %>%
  mutate(idx = row_number()) %>% 
  tidyr::spread(cell_type,symbol,fill = NA) %>%
  dplyr::select(-idx) %>%
  write.csv("CellMarker_markers.csv",na="",row.names = F)

```

```{r,echo=F,eval=F,message=F,warning=F,error=F}
# Only combine cellmatch and panlaoDB

#remotes::install_gitlab("hrbrmstr/pluralize")
library(pluralize)

# convert plural to singular
result_marker <- cellmatch %>%
  bind_rows(panlao) %>%
  mutate(
    cell_type = singularize(.$cell_type)
  ) %>%
  mutate(symbol = str_replace_all(symbol, "\\[|\\]", "")) %>%
  filter(symbol != "NA") %>%
  unique() %>%
  write_csv("mingtao_notch1_marker.csv")

 
result_marker %>%
  group_by(cell_type) %>%
  mutate(idx = row_number()) %>% 
  mutate(symbol = toupper(symbol)) %>%
  tidyr::spread(cell_type,symbol) %>%
  dplyr::select(-idx) %>%
  write_csv("mingtao_notch1_marker_SCINA.csv")
  

```


